
import type { Metadata } from "next";
import "./globals.scss";
import ContextLayout from "./ContextLayout";


export const metadata: Metadata = {
  title: "MugStyle e-shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="fr">
      <ContextLayout>
        {children}
      </ContextLayout>
    </html>
  );
}
